/**
 * Категории специалистов — единственный источник правды.
 *
 * Раньше этот список жил внутри страницы /hire, а каталог и футер держали свои
 * копии, которые между собой не совпадали. Теперь им пользуются все: страницы
 * категорий, каталог, футер и карта сайта.
 *
 * `name` — английское название: оно уходит в запрос к API и в поиск, поэтому
 * переводить его нельзя, иначе фильтр перестанет находить людей. Для показа
 * человеку берётся перевод по `nameKey` из раздела hire.
 */
export type Category = {
  /** Часть адреса: /browse/ai-automation */
  slug: string;
  /** Английское название — значение фильтра, не для показа. */
  name: string;
  /** Ключ перевода в разделе hire. */
  nameKey: string;
  /** Типовые роли внутри категории; переводятся через SKILL_KEYS. */
  skills: string[];
};

export const CATEGORIES: Category[] = [
  {
    slug: "ai-automation",
    name: "AI & Automation",
    nameKey: "c1",
    skills: [
      "AI Developers",
      "Machine Learning Engineers",
      "Chatbot Developers",
      "Computer Vision Engineers",
      "NLP Engineers",
      "Prompt Engineers",
      "AI Integration Developers",
      "Automation Experts",
      "OpenAI API Developers",
      "LLM Fine-tuning Specialists",
      "n8n / Make / Zapier Experts",
      "AI Consultants",
      "Stable Diffusion Artists",
      "AI Voice Cloning Experts",
      "AI Data Labeling Specialists",
      "Reinforcement Learning Engineers",
      "AI Workflow Architects",
      "Generative AI Developers",
      "AI Product Managers",
      "Agentic AI Developers",
    ],
  },
  {
    slug: "programming",
    name: "Programming & Development",
    nameKey: "c2",
    skills: [
      "Full-Stack Developers",
      "Backend Developers",
      "Python Developers",
      "React / Next.js Developers",
      "Node.js Developers",
      "API Developers",
      "Cloud & DevOps Engineers",
      "Mobile App Developers",
      "FastAPI Developers",
      "Django Developers",
      "Docker & Kubernetes Experts",
      "AWS / GCP / Azure Engineers",
      "Blockchain & Web3 Developers",
      "Cybersecurity Specialists",
      "WordPress Developers",
      "Shopify Developers",
      "TypeScript Developers",
      "GraphQL Developers",
      "WebSocket Engineers",
      "Microservices Architects",
    ],
  },
  {
    slug: "data-science",
    name: "Data Science & Analytics",
    nameKey: "c3",
    skills: [
      "Data Scientists",
      "ML Engineers",
      "Data Analysts",
      "Data Engineers",
      "Business Intelligence Analysts",
      "MLOps Engineers",
      "Statistical Modelers",
      "AI Researchers",
      "Pandas / NumPy Experts",
      "TensorFlow / PyTorch Developers",
      "Apache Spark Engineers",
      "SQL / NoSQL Specialists",
      "Power BI / Tableau Analysts",
      "A/B Testing Specialists",
      "Forecasting & Time Series Experts",
      "Kaggle Competition Winners",
      "Quantitative Analysts",
      "Data Pipeline Architects",
      "Feature Engineering Specialists",
      "Model Evaluation Experts",
    ],
  },
  {
    slug: "design",
    name: "Design & Creative AI",
    nameKey: "c4",
    skills: [
      "UI/UX Designers",
      "AI Image Generation Artists",
      "Logo & Brand Designers",
      "Motion Designers",
      "Midjourney Prompt Artists",
      "DALL-E / Firefly Artists",
      "AI Video Creators",
      "3D AI Artists",
      "Product Designers",
      "Presentation Designers",
      "Graphic Designers",
      "AI Art Directors",
      "Web Designers",
      "Figma Designers",
      "Brand Identity Designers",
      "Social Media Designers",
      "Packaging Designers",
      "AR / VR Designers",
      "AI Style Transfer Artists",
      "Illustration Specialists",
    ],
  },
  {
    slug: "content",
    name: "Content & Writing AI",
    nameKey: "c5",
    skills: [
      "AI Content Creators",
      "Copywriters",
      "Technical Writers",
      "SEO Content Strategists",
      "AI-Assisted Translators",
      "Script Writers",
      "Blog & Article Writers",
      "Ghostwriters",
      "Email Copywriters",
      "LinkedIn Content Creators",
      "Grant Writers",
      "Legal Document Writers",
      "Product Description Writers",
      "UX Writers",
      "AI Prompt Writers",
      "Multilingual Content Specialists",
      "Proofreaders & Editors",
      "Podcast Script Writers",
      "White Paper Authors",
      "Case Study Writers",
    ],
  },
  {
    slug: "marketing",
    name: "Marketing & Growth AI",
    nameKey: "c6",
    skills: [
      "AI Marketing Strategists",
      "SEO Specialists",
      "PPC & Google Ads Experts",
      "Social Media AI Managers",
      "Email Marketing Automation Experts",
      "Growth Hackers",
      "CRO Specialists",
      "AI Ad Copywriters",
      "Affiliate Marketing Experts",
      "Influencer Marketing Managers",
      "Brand Strategists",
      "Lead Generation Specialists",
      "TikTok & YouTube Strategists",
      "Marketing Analytics Experts",
      "Content Marketing Managers",
      "AI-Powered PR Specialists",
      "Programmatic Advertising Experts",
      "Conversion Funnel Specialists",
      "Community Managers",
      "Performance Marketers",
    ],
  },
  {
    slug: "video-audio",
    name: "Video & Audio AI",
    nameKey: "c7",
    skills: [
      "AI Video Editors",
      "AI Video Generators",
      "Voice-over Artists",
      "AI Music Composers",
      "Podcast Producers",
      "Motion Graphics Artists",
      "Audio Engineers",
      "YouTube Channel Managers",
      "Sora / Runway ML Experts",
      "ElevenLabs Voice Specialists",
      "Subtitling & Captioning Experts",
      "Video Scriptwriters",
      "Short-Form Content Creators",
      "Documentary Editors",
      "Sound Designers",
      "AI Dubbing Specialists",
      "Explainer Video Creators",
      "Product Demo Video Producers",
      "VFX Artists",
      "Live Streaming Experts",
    ],
  },
  {
    slug: "industry",
    name: "Industry AI Solutions",
    nameKey: "c8",
    skills: [
      "Healthcare AI Developers",
      "FinTech AI Specialists",
      "Legal AI & LegalTech Experts",
      "Retail & E-Commerce AI Developers",
      "EdTech AI Developers",
      "Agriculture & Precision Farming AI",
      "Manufacturing & Industry 4.0 AI",
      "Real Estate PropTech AI",
      "Energy & Smart Grid AI Engineers",
      "Logistics & Supply Chain AI",
      "HR & Recruitment AI Specialists",
      "Cybersecurity AI Experts",
      "Insurance AI Actuaries",
      "Pharmaceutical AI Researchers",
      "Autonomous Vehicle AI Engineers",
      "Smart City AI Consultants",
      "Climate & Environmental AI Researchers",
      "Media & Entertainment AI Developers",
      "Sports Analytics AI Specialists",
      "Government & Public Sector AI",
    ],
  },
  {
    slug: "business",
    name: "Business & Strategy AI",
    nameKey: "c9",
    skills: [
      "AI Business Analysts",
      "AI Project Managers",
      "AI Product Managers",
      "Enterprise AI Architects",
      "AI Ethics & Governance Consultants",
      "CRM Automation Experts",
      "AI Workflow Consultants",
      "Digital Transformation Specialists",
      "Virtual AI Assistants",
      "AI Procurement Specialists",
      "Change Management Consultants",
      "AI ROI Analysts",
      "Technology Roadmap Consultants",
      "AI Vendor Assessment Specialists",
      "Process Mining Experts",
      "AI Training & Coaching",
      "Board-level AI Advisors",
      "AI Policy Consultants",
      "Innovation Managers",
      "AI Startup Mentors",
    ],
  },
];

export const CATEGORY_SLUGS = CATEGORIES.map((c) => c.slug);

export function categoryBySlug(slug: string): Category | undefined {
  return CATEGORIES.find((c) => c.slug === slug);
}

/** Английские названия ролей категории — по ним фильтрует сервер. */
export function skillsOf(slug: string): string[] {
  return categoryBySlug(slug)?.skills ?? [];
}
