/**
 * Английское название роли → ключ перевода.
 *
 * Разделение нужно, чтобы подпись переводилась, а в поиск и в фильтр уходило
 * английское название: иначе на любом языке, кроме английского, каталог
 * перестал бы находить людей.
 */
export const SKILL_KEYS: Record<string, string> = {
  "AI Developers": "aiDevelopers",
  "Machine Learning Engineers": "machineLearningEngineers",
  "Chatbot Developers": "chatbotDevelopers",
  "Computer Vision Engineers": "computerVisionEngineers",
  "Prompt Engineers": "promptEngineers",
  "AI Integration Developers": "aiIntegrationDevelopers",
  "Automation Experts": "automationExperts",
  "AI Consultants": "aiConsultants",
  "AI Voice Cloning Experts": "aiVoiceCloningExperts",
  "AI Data Labeling Specialists": "aiDataLabelingSpecialists",
  "Reinforcement Learning Engineers": "reinforcementLearningEngineers",
  "AI Workflow Architects": "aiWorkflowArchitects",
  "Generative AI Developers": "generativeAiDevelopers",
  "AI Product Managers": "aiProductManagers",
  "Agentic AI Developers": "agenticAiDevelopers",
  "Full-Stack Developers": "fullStackDevelopers",
  "Backend Developers": "backendDevelopers",
  "Cloud & DevOps Engineers": "cloudDevopsEngineers",
  "Mobile App Developers": "mobileAppDevelopers",
  "Cybersecurity Specialists": "cybersecuritySpecialists",
  "Microservices Architects": "microservicesArchitects",
  "Data Scientists": "dataScientists",
  "ML Engineers": "mlEngineers",
  "Data Analysts": "dataAnalysts",
  "Data Engineers": "dataEngineers",
  "Business Intelligence Analysts": "businessIntelligenceAnalysts",
  "Statistical Modelers": "statisticalModelers",
  "AI Researchers": "aiResearchers",
  "Forecasting & Time Series Experts": "forecastingTimeSeriesExperts",
  "Quantitative Analysts": "quantitativeAnalysts",
  "Data Pipeline Architects": "dataPipelineArchitects",
  "Feature Engineering Specialists": "featureEngineeringSpecialists",
  "Model Evaluation Experts": "modelEvaluationExperts",
  "UI/UX Designers": "uiUxDesigners",
  "AI Image Generation Artists": "aiImageGenerationArtists",
  "Logo & Brand Designers": "logoBrandDesigners",
  "Motion Designers": "motionDesigners",
  "AI Video Creators": "aiVideoCreators",
  "3D AI Artists": "3dAiArtists",
  "Product Designers": "productDesigners",
  "Presentation Designers": "presentationDesigners",
  "Graphic Designers": "graphicDesigners",
  "AI Art Directors": "aiArtDirectors",
  "Web Designers": "webDesigners",
  "Brand Identity Designers": "brandIdentityDesigners",
  "Social Media Designers": "socialMediaDesigners",
  "Packaging Designers": "packagingDesigners",
  "AR / VR Designers": "arVrDesigners",
  "AI Style Transfer Artists": "aiStyleTransferArtists",
  "Illustration Specialists": "illustrationSpecialists",
  "AI Content Creators": "aiContentCreators",
  "Copywriters": "copywriters",
  "Technical Writers": "technicalWriters",
  "AI-Assisted Translators": "aiAssistedTranslators",
  "Script Writers": "scriptWriters",
  "Blog & Article Writers": "blogArticleWriters",
  "Ghostwriters": "ghostwriters",
  "Email Copywriters": "emailCopywriters",
  "LinkedIn Content Creators": "linkedinContentCreators",
  "Grant Writers": "grantWriters",
  "Legal Document Writers": "legalDocumentWriters",
  "Product Description Writers": "productDescriptionWriters",
  "UX Writers": "uxWriters",
  "AI Prompt Writers": "aiPromptWriters",
  "Multilingual Content Specialists": "multilingualContentSpecialists",
  "Proofreaders & Editors": "proofreadersEditors",
  "Podcast Script Writers": "podcastScriptWriters",
  "White Paper Authors": "whitePaperAuthors",
  "Case Study Writers": "caseStudyWriters",
  "AI Marketing Strategists": "aiMarketingStrategists",
  "PPC & Google Ads Experts": "ppcGoogleAdsExperts",
  "Social Media AI Managers": "socialMediaAiManagers",
  "Email Marketing Automation Experts": "emailMarketingAutomationExperts",
  "Growth Hackers": "growthHackers",
  "CRO Specialists": "croSpecialists",
  "AI Ad Copywriters": "aiAdCopywriters",
  "Affiliate Marketing Experts": "affiliateMarketingExperts",
  "Influencer Marketing Managers": "influencerMarketingManagers",
  "Brand Strategists": "brandStrategists",
  "Lead Generation Specialists": "leadGenerationSpecialists",
  "TikTok & YouTube Strategists": "tiktokYoutubeStrategists",
  "Marketing Analytics Experts": "marketingAnalyticsExperts",
  "Content Marketing Managers": "contentMarketingManagers",
  "AI-Powered PR Specialists": "aiPoweredPrSpecialists",
  "Programmatic Advertising Experts": "programmaticAdvertisingExperts",
  "Conversion Funnel Specialists": "conversionFunnelSpecialists",
  "Community Managers": "communityManagers",
  "Performance Marketers": "performanceMarketers",
  "AI Video Editors": "aiVideoEditors",
  "AI Video Generators": "aiVideoGenerators",
  "Voice-over Artists": "voiceOverArtists",
  "AI Music Composers": "aiMusicComposers",
  "Podcast Producers": "podcastProducers",
  "Motion Graphics Artists": "motionGraphicsArtists",
  "Audio Engineers": "audioEngineers",
  "YouTube Channel Managers": "youtubeChannelManagers",
  "Subtitling & Captioning Experts": "subtitlingCaptioningExperts",
  "Video Scriptwriters": "videoScriptwriters",
  "Short-Form Content Creators": "shortFormContentCreators",
  "Documentary Editors": "documentaryEditors",
  "Sound Designers": "soundDesigners",
  "AI Dubbing Specialists": "aiDubbingSpecialists",
  "Explainer Video Creators": "explainerVideoCreators",
  "Product Demo Video Producers": "productDemoVideoProducers",
  "VFX Artists": "vfxArtists",
  "Live Streaming Experts": "liveStreamingExperts",
  "Healthcare AI Developers": "healthcareAiDevelopers",
  "FinTech AI Specialists": "fintechAiSpecialists",
  "Legal AI & LegalTech Experts": "legalAiLegaltechExperts",
  "Retail & E-Commerce AI Developers": "retailECommerceAiDevelopers",
  "EdTech AI Developers": "edtechAiDevelopers",
  "Agriculture & Precision Farming AI": "agriculturePrecisionFarmingAi",
  "Manufacturing & Industry 4.0 AI": "manufacturingIndustry40Ai",
  "Real Estate PropTech AI": "realEstateProptechAi",
  "Energy & Smart Grid AI Engineers": "energySmartGridAiEngineers",
  "Logistics & Supply Chain AI": "logisticsSupplyChainAi",
  "HR & Recruitment AI Specialists": "hrRecruitmentAiSpecialists",
  "Cybersecurity AI Experts": "cybersecurityAiExperts",
  "Insurance AI Actuaries": "insuranceAiActuaries",
  "Pharmaceutical AI Researchers": "pharmaceuticalAiResearchers",
  "Autonomous Vehicle AI Engineers": "autonomousVehicleAiEngineers",
  "Smart City AI Consultants": "smartCityAiConsultants",
  "Climate & Environmental AI Researchers": "climateEnvironmentalAiResearchers",
  "Media & Entertainment AI Developers": "mediaEntertainmentAiDevelopers",
  "Sports Analytics AI Specialists": "sportsAnalyticsAiSpecialists",
  "Government & Public Sector AI": "governmentPublicSectorAi",
  "AI Business Analysts": "aiBusinessAnalysts",
  "AI Project Managers": "aiProjectManagers",
  "Enterprise AI Architects": "enterpriseAiArchitects",
  "AI Ethics & Governance Consultants": "aiEthicsGovernanceConsultants",
  "AI Workflow Consultants": "aiWorkflowConsultants",
  "Digital Transformation Specialists": "digitalTransformationSpecialists",
  "Virtual AI Assistants": "virtualAiAssistants",
  "AI Procurement Specialists": "aiProcurementSpecialists",
  "Change Management Consultants": "changeManagementConsultants",
  "AI ROI Analysts": "aiRoiAnalysts",
  "Technology Roadmap Consultants": "technologyRoadmapConsultants",
  "AI Vendor Assessment Specialists": "aiVendorAssessmentSpecialists",
  "Process Mining Experts": "processMiningExperts",
  "AI Training & Coaching": "aiTrainingCoaching",
  "Board-level AI Advisors": "boardLevelAiAdvisors",
  "AI Policy Consultants": "aiPolicyConsultants",
  "Innovation Managers": "innovationManagers",
  "AI Startup Mentors": "aiStartupMentors",
  "A/B Testing Specialists": "abTesting",
  "API Developers": "apiDevelopers",
  "AWS / GCP / Azure Engineers": "cloudEngineers",
  "Apache Spark Engineers": "sparkEngineers",
  "Blockchain & Web3 Developers": "web3Developers",
  "CRM Automation Experts": "crmAutomation",
  "DALL-E / Firefly Artists": "dalleArtists",
  "Django Developers": "djangoDevelopers",
  "Docker & Kubernetes Experts": "k8sExperts",
  "ElevenLabs Voice Specialists": "elevenlabs",
  "FastAPI Developers": "fastapiDevelopers",
  "Figma Designers": "figmaDesigners",
  "GraphQL Developers": "graphqlDevelopers",
  "Kaggle Competition Winners": "kaggleWinners",
  "LLM Fine-tuning Specialists": "llmFinetuning",
  "MLOps Engineers": "mlopsEngineers",
  "Midjourney Prompt Artists": "midjourney",
  "NLP Engineers": "nlpEngineers",
  "Node.js Developers": "nodeDevelopers",
  "OpenAI API Developers": "openaiDevelopers",
  "Pandas / NumPy Experts": "pandasExperts",
  "Power BI / Tableau Analysts": "biAnalysts",
  "Python Developers": "pythonDevelopers",
  "React / Next.js Developers": "reactDevelopers",
  "SEO Content Strategists": "seoStrategists",
  "SEO Specialists": "seoSpecialists",
  "SQL / NoSQL Specialists": "sqlSpecialists",
  "Shopify Developers": "shopifyDevelopers",
  "Sora / Runway ML Experts": "soraExperts",
  "Stable Diffusion Artists": "sdArtists",
  "TensorFlow / PyTorch Developers": "tfDevelopers",
  "TypeScript Developers": "tsDevelopers",
  "WebSocket Engineers": "wsEngineers",
  "WordPress Developers": "wpDevelopers",
  "n8n / Make / Zapier Experts": "noCodeExperts",
};

/** Ключ перевода для роли; если роли нет в словаре — показываем как есть. */
export function skillKey(skill: string): string | undefined {
  return SKILL_KEYS[skill];
}
