/**
 * Категория → роли внутри неё.
 *
 * Копия списка из клиента (client/src/lib/categories.ts): сервер не может
 * импортировать код из соседнего пакета, а фильтровать по категории он должен
 * сам — иначе поисковик увидит на странице категории весь каталог целиком.
 * При изменении списка править оба файла.
 */
export const CATEGORY_SKILLS: Record<string, string[]> = {
  'ai-automation': [
    'AI Developers',
    'Machine Learning Engineers',
    'Chatbot Developers',
    'Computer Vision Engineers',
    'NLP Engineers',
    'Prompt Engineers',
    'AI Integration Developers',
    'Automation Experts',
    'OpenAI API Developers',
    'LLM Fine-tuning Specialists',
    'n8n / Make / Zapier Experts',
    'AI Consultants',
    'Stable Diffusion Artists',
    'AI Voice Cloning Experts',
    'AI Data Labeling Specialists',
    'Reinforcement Learning Engineers',
    'AI Workflow Architects',
    'Generative AI Developers',
    'AI Product Managers',
    'Agentic AI Developers',
  ],
  'programming': [
    'Full-Stack Developers',
    'Backend Developers',
    'Python Developers',
    'React / Next.js Developers',
    'Node.js Developers',
    'API Developers',
    'Cloud & DevOps Engineers',
    'Mobile App Developers',
    'FastAPI Developers',
    'Django Developers',
    'Docker & Kubernetes Experts',
    'AWS / GCP / Azure Engineers',
    'Blockchain & Web3 Developers',
    'Cybersecurity Specialists',
    'WordPress Developers',
    'Shopify Developers',
    'TypeScript Developers',
    'GraphQL Developers',
    'WebSocket Engineers',
    'Microservices Architects',
  ],
  'data-science': [
    'Data Scientists',
    'ML Engineers',
    'Data Analysts',
    'Data Engineers',
    'Business Intelligence Analysts',
    'MLOps Engineers',
    'Statistical Modelers',
    'AI Researchers',
    'Pandas / NumPy Experts',
    'TensorFlow / PyTorch Developers',
    'Apache Spark Engineers',
    'SQL / NoSQL Specialists',
    'Power BI / Tableau Analysts',
    'A/B Testing Specialists',
    'Forecasting & Time Series Experts',
    'Kaggle Competition Winners',
    'Quantitative Analysts',
    'Data Pipeline Architects',
    'Feature Engineering Specialists',
    'Model Evaluation Experts',
  ],
  'design': [
    'UI/UX Designers',
    'AI Image Generation Artists',
    'Logo & Brand Designers',
    'Motion Designers',
    'Midjourney Prompt Artists',
    'DALL-E / Firefly Artists',
    'AI Video Creators',
    '3D AI Artists',
    'Product Designers',
    'Presentation Designers',
    'Graphic Designers',
    'AI Art Directors',
    'Web Designers',
    'Figma Designers',
    'Brand Identity Designers',
    'Social Media Designers',
    'Packaging Designers',
    'AR / VR Designers',
    'AI Style Transfer Artists',
    'Illustration Specialists',
  ],
  'content': [
    'AI Content Creators',
    'Copywriters',
    'Technical Writers',
    'SEO Content Strategists',
    'AI-Assisted Translators',
    'Script Writers',
    'Blog & Article Writers',
    'Ghostwriters',
    'Email Copywriters',
    'LinkedIn Content Creators',
    'Grant Writers',
    'Legal Document Writers',
    'Product Description Writers',
    'UX Writers',
    'AI Prompt Writers',
    'Multilingual Content Specialists',
    'Proofreaders & Editors',
    'Podcast Script Writers',
    'White Paper Authors',
    'Case Study Writers',
  ],
  'marketing': [
    'AI Marketing Strategists',
    'SEO Specialists',
    'PPC & Google Ads Experts',
    'Social Media AI Managers',
    'Email Marketing Automation Experts',
    'Growth Hackers',
    'CRO Specialists',
    'AI Ad Copywriters',
    'Affiliate Marketing Experts',
    'Influencer Marketing Managers',
    'Brand Strategists',
    'Lead Generation Specialists',
    'TikTok & YouTube Strategists',
    'Marketing Analytics Experts',
    'Content Marketing Managers',
    'AI-Powered PR Specialists',
    'Programmatic Advertising Experts',
    'Conversion Funnel Specialists',
    'Community Managers',
    'Performance Marketers',
  ],
  'video-audio': [
    'AI Video Editors',
    'AI Video Generators',
    'Voice-over Artists',
    'AI Music Composers',
    'Podcast Producers',
    'Motion Graphics Artists',
    'Audio Engineers',
    'YouTube Channel Managers',
    'Sora / Runway ML Experts',
    'ElevenLabs Voice Specialists',
    'Subtitling & Captioning Experts',
    'Video Scriptwriters',
    'Short-Form Content Creators',
    'Documentary Editors',
    'Sound Designers',
    'AI Dubbing Specialists',
    'Explainer Video Creators',
    'Product Demo Video Producers',
    'VFX Artists',
    'Live Streaming Experts',
  ],
  'industry': [
    'Healthcare AI Developers',
    'FinTech AI Specialists',
    'Legal AI & LegalTech Experts',
    'Retail & E-Commerce AI Developers',
    'EdTech AI Developers',
    'Agriculture & Precision Farming AI',
    'Manufacturing & Industry 4.0 AI',
    'Real Estate PropTech AI',
    'Energy & Smart Grid AI Engineers',
    'Logistics & Supply Chain AI',
    'HR & Recruitment AI Specialists',
    'Cybersecurity AI Experts',
    'Insurance AI Actuaries',
    'Pharmaceutical AI Researchers',
    'Autonomous Vehicle AI Engineers',
    'Smart City AI Consultants',
    'Climate & Environmental AI Researchers',
    'Media & Entertainment AI Developers',
    'Sports Analytics AI Specialists',
    'Government & Public Sector AI',
  ],
  'business': [
    'AI Business Analysts',
    'AI Project Managers',
    'AI Product Managers',
    'Enterprise AI Architects',
    'AI Ethics & Governance Consultants',
    'CRM Automation Experts',
    'AI Workflow Consultants',
    'Digital Transformation Specialists',
    'Virtual AI Assistants',
    'AI Procurement Specialists',
    'Change Management Consultants',
    'AI ROI Analysts',
    'Technology Roadmap Consultants',
    'AI Vendor Assessment Specialists',
    'Process Mining Experts',
    'AI Training & Coaching',
    'Board-level AI Advisors',
    'AI Policy Consultants',
    'Innovation Managers',
    'AI Startup Mentors',
  ],
};

export const CATEGORY_SLUGS = Object.keys(CATEGORY_SKILLS);
